setono_sylius_facebook_admin_pixel:
    resource: |
        section: admin
        alias: setono_sylius_facebook.pixel
        permission: true
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: setono_sylius_facebook_admin_pixel
        vars:
            all:
                subheader: setono_sylius_facebook.ui.manage_pixels
                templates:
                    form: "@SetonoSyliusFacebookPlugin/Admin/Pixel/_form.html.twig"
            index:
                icon: 'facebook'
    type: sylius.resource
